<?php

function carimus_setup_headless_theme() {
    add_theme_support('post-thumbnails');
}
add_action('after_setup_theme', 'carimus_setup_headless_theme');


add_action( 'init', function() {
    register_nav_menu('main-nav',__( 'Main Nav' ));
});

// Register Custom Post Types
require_once(__DIR__ . '/custom-post-types.php');
add_action('init', function() {
    if( function_exists('acf_add_options_page') ) {
        acf_add_options_page(array(
            'page_title' 	=> 'Theme Settings',
            'menu_title'	=> 'Theme Settings',
            'menu_slug' 	=> 'theme-settings',
            'capability'	=> 'edit_posts',
            'redirect'		=> false,
            'show_in_graphql' => true,
            'type' => 'options_page',
        ));
    }
});

//if( function_exists('acf_add_local_field_group') ):
//
//	acf_add_local_field_group(array(
//		'key' => 'group_609071904bbe5',
//		'title' => 'Page Sections',
//		'fields' => array(
//			array(
//				'key' => 'field_6091057be1dbc',
//				'label' => 'Page Sections',
//				'name' => 'page_sections',
//				'type' => 'flexible_content',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'show_in_graphql' => 1,
//				'layouts' => array(
//					'layout_609105f7e9c9d' => array(
//						'key' => 'layout_609105f7e9c9d',
//						'name' => 'TextWithImage',
//						'label' => 'Text With Image',
//						'display' => 'row',
//						'sub_fields' => array(
//							array(
//								'key' => 'field_6091066ce1dbd',
//								'label' => 'Section Title',
//								'name' => 'section_title',
//								'type' => 'text',
//								'instructions' => '',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'default_value' => '',
//								'placeholder' => '',
//								'prepend' => '',
//								'append' => '',
//								'maxlength' => '',
//							),
//							array(
//								'key' => 'field_609108aee1dbe',
//								'label' => 'Background Color',
//								'name' => 'background_color',
//								'type' => 'color_picker',
//								'instructions' => '',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'default_value' => '',
//							),
//							array(
//								'key' => 'field_60910d0165760',
//								'label' => 'Dark Background',
//								'name' => 'text_light',
//								'type' => 'true_false',
//								'instructions' => 'Toggle to make the font white for the section',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'message' => '',
//								'default_value' => 0,
//								'ui' => 0,
//								'ui_on_text' => '',
//								'ui_off_text' => '',
//							),
//							array(
//								'key' => 'field_609108e3e1dbf',
//								'label' => 'Image on Right',
//								'name' => 'image_on_right',
//								'type' => 'true_false',
//								'instructions' => 'Change Image to be on the right instead of the left',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'message' => '',
//								'default_value' => 0,
//								'ui' => 0,
//								'ui_on_text' => '',
//								'ui_off_text' => '',
//							),
//							array(
//								'key' => 'field_60910904e1dc0',
//								'label' => 'Image',
//								'name' => 'image',
//								'type' => 'image',
//								'instructions' => '',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'return_format' => '',
//								'preview_size' => 'medium',
//								'library' => '',
//								'min_width' => '',
//								'min_height' => '',
//								'min_size' => '',
//								'max_width' => '',
//								'max_height' => '',
//								'max_size' => '',
//								'mime_types' => '',
//							),
//							array(
//								'key' => 'field_6091091fe1dc1',
//								'label' => 'Content',
//								'name' => 'content',
//								'type' => 'wysiwyg',
//								'instructions' => '',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'default_value' => '',
//								'tabs' => 'all',
//								'toolbar' => 'full',
//								'media_upload' => 1,
//								'delay' => 0,
//							),
//							array(
//								'key' => 'field_60910a80e1dc4',
//								'label' => 'Section Link',
//								'name' => 'section_link',
//								'type' => 'link',
//								'instructions' => '',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'return_format' => '',
//							),
//						),
//						'min' => '',
//						'max' => '',
//					),
//					'layout_60910b3ae1dca' => array(
//						'key' => 'layout_60910b3ae1dca',
//						'name' => 'TextColumns',
//						'label' => 'Text Columns',
//						'display' => 'row',
//						'sub_fields' => array(
//							array(
//								'key' => 'field_60910b3ae1dcb',
//								'label' => 'Section Title',
//								'name' => 'section_title',
//								'type' => 'text',
//								'instructions' => '',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'default_value' => '',
//								'placeholder' => '',
//								'prepend' => '',
//								'append' => '',
//								'maxlength' => '',
//							),
//							array(
//								'key' => 'field_60910b3ae1dcc',
//								'label' => 'Background Color',
//								'name' => 'background_color',
//								'type' => 'color_picker',
//								'instructions' => '',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'default_value' => '',
//							),
//							array(
//								'key' => 'field_60910d7727027',
//								'label' => 'Dark Background',
//								'name' => 'text_light',
//								'type' => 'true_false',
//								'instructions' => 'Toggle to make the font white for the section',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'message' => '',
//								'default_value' => 0,
//								'ui' => 0,
//								'ui_on_text' => '',
//								'ui_off_text' => '',
//							),
//							array(
//								'key' => 'field_6092f530acd7e',
//								'label' => 'Link Button Instead',
//								'name' => 'link_button_instead',
//								'type' => 'true_false',
//								'instructions' => 'Toggle to switch from normal button to a link button',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'message' => '',
//								'default_value' => 0,
//								'ui' => 0,
//								'ui_on_text' => '',
//								'ui_off_text' => '',
//							),
//							array(
//								'key' => 'field_60910b8be1dd1',
//								'label' => 'Columns',
//								'name' => 'columns',
//								'type' => 'repeater',
//								'instructions' => 'Add up to 4 Columns',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'collapsed' => '',
//								'min' => 0,
//								'max' => 4,
//								'layout' => 'row',
//								'button_label' => 'Add Column',
//								'sub_fields' => array(
//									array(
//										'key' => 'field_60910ba3e1dd2',
//										'label' => 'Column',
//										'name' => 'column',
//										'type' => 'wysiwyg',
//										'instructions' => '',
//										'required' => 0,
//										'conditional_logic' => 0,
//										'wrapper' => array(
//											'width' => '',
//											'class' => '',
//											'id' => '',
//										),
//										'show_in_graphql' => 1,
//										'default_value' => '',
//										'tabs' => 'all',
//										'toolbar' => 'full',
//										'media_upload' => 1,
//										'delay' => 0,
//									),
//									array(
//										'key' => 'field_6092f4abead39',
//										'label' => 'Section Link',
//										'name' => 'section_link',
//										'type' => 'link',
//										'instructions' => '',
//										'required' => 0,
//										'conditional_logic' => 0,
//										'wrapper' => array(
//											'width' => '',
//											'class' => '',
//											'id' => '',
//										),
//										'show_in_graphql' => 1,
//										'return_format' => 'array',
//									),
//								),
//							),
//						),
//						'min' => '',
//						'max' => '',
//					),
//					'layout_60929c689cb9a' => array(
//						'key' => 'layout_60929c689cb9a',
//						'name' => 'ValuesCards',
//						'label' => 'Values Cards',
//						'display' => 'row',
//						'sub_fields' => array(
//							array(
//								'key' => 'field_60929c689cb9b',
//								'label' => 'Section Title',
//								'name' => 'section_title',
//								'type' => 'text',
//								'instructions' => '',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'default_value' => '',
//								'placeholder' => '',
//								'prepend' => '',
//								'append' => '',
//								'maxlength' => '',
//							),
//							array(
//								'key' => 'field_60929c689cb9c',
//								'label' => 'Background Color',
//								'name' => 'background_color',
//								'type' => 'color_picker',
//								'instructions' => '',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'default_value' => '',
//							),
//							array(
//								'key' => 'field_60929c689cb9d',
//								'label' => 'Dark Background',
//								'name' => 'text_light',
//								'type' => 'true_false',
//								'instructions' => 'Toggle to make the font white for the section',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'message' => '',
//								'default_value' => 0,
//								'ui' => 0,
//								'ui_on_text' => '',
//								'ui_off_text' => '',
//							),
//							array(
//								'key' => 'field_60929c689cb9f',
//								'label' => 'Values Cards',
//								'name' => 'values_cards',
//								'type' => 'repeater',
//								'instructions' => '',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'collapsed' => '',
//								'min' => 0,
//								'max' => 0,
//								'layout' => 'row',
//								'button_label' => 'Add Card',
//								'sub_fields' => array(
//									array(
//										'key' => 'field_60929c689cba0',
//										'label' => 'Value Title',
//										'name' => 'value_title',
//										'type' => 'text',
//										'instructions' => '',
//										'required' => 0,
//										'conditional_logic' => 0,
//										'wrapper' => array(
//											'width' => '',
//											'class' => '',
//											'id' => '',
//										),
//										'show_in_graphql' => 1,
//										'default_value' => '',
//										'placeholder' => '',
//										'prepend' => '',
//										'append' => '',
//										'maxlength' => '',
//									),
//									array(
//										'key' => 'field_60929d6c9cba1',
//										'label' => 'Value Summary',
//										'name' => 'value_summary',
//										'type' => 'textarea',
//										'instructions' => '',
//										'required' => 0,
//										'conditional_logic' => 0,
//										'wrapper' => array(
//											'width' => '',
//											'class' => '',
//											'id' => '',
//										),
//										'show_in_graphql' => 1,
//										'default_value' => '',
//										'placeholder' => '',
//										'maxlength' => '',
//										'rows' => '',
//										'new_lines' => '',
//									),
//									array(
//										'key' => 'field_60929d7e9cba2',
//										'label' => 'Background Image',
//										'name' => 'background_image',
//										'type' => 'image',
//										'instructions' => '',
//										'required' => 0,
//										'conditional_logic' => 0,
//										'wrapper' => array(
//											'width' => '',
//											'class' => '',
//											'id' => '',
//										),
//										'show_in_graphql' => 1,
//										'return_format' => 'array',
//										'preview_size' => 'medium',
//										'library' => 'all',
//										'min_width' => '',
//										'min_height' => '',
//										'min_size' => '',
//										'max_width' => '',
//										'max_height' => '',
//										'max_size' => '',
//										'mime_types' => '',
//									),
//								),
//							),
//						),
//						'min' => '',
//						'max' => '',
//					),
//					'layout_609109afe1dc3' => array(
//						'key' => 'layout_609109afe1dc3',
//						'name' => 'LogosWithContent',
//						'label' => 'Logos with Content',
//						'display' => 'row',
//						'sub_fields' => array(
//							array(
//								'key' => 'field_60910a94e1dc5',
//								'label' => 'Section Title',
//								'name' => 'section_title',
//								'type' => 'text',
//								'instructions' => '',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'default_value' => '',
//								'placeholder' => '',
//								'prepend' => '',
//								'append' => '',
//								'maxlength' => '',
//							),
//							array(
//								'key' => 'field_60910aade1dc6',
//								'label' => 'Background Color',
//								'name' => 'background_color',
//								'type' => 'color_picker',
//								'instructions' => '',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'default_value' => '',
//							),
//							array(
//								'key' => 'field_60910d9b27028',
//								'label' => 'Dark Background',
//								'name' => 'text_light',
//								'type' => 'true_false',
//								'instructions' => 'Toggle to make the font white for the section',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'message' => '',
//								'default_value' => 0,
//								'ui' => 0,
//								'ui_on_text' => '',
//								'ui_off_text' => '',
//							),
//							array(
//								'key' => 'field_60910ad7e1dc7',
//								'label' => 'Content',
//								'name' => 'content',
//								'type' => 'wysiwyg',
//								'instructions' => '',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'default_value' => '',
//								'tabs' => 'all',
//								'toolbar' => 'full',
//								'media_upload' => 1,
//								'delay' => 0,
//							),
//							array(
//								'key' => 'field_60910ae9e1dc8',
//								'label' => 'Logos',
//								'name' => 'logos',
//								'type' => 'repeater',
//								'instructions' => '',
//								'required' => 0,
//								'conditional_logic' => 0,
//								'wrapper' => array(
//									'width' => '',
//									'class' => '',
//									'id' => '',
//								),
//								'show_in_graphql' => 1,
//								'collapsed' => '',
//								'min' => 0,
//								'max' => 0,
//								'layout' => 'row',
//								'button_label' => '',
//								'sub_fields' => array(
//									array(
//										'key' => 'field_60910afee1dc9',
//										'label' => 'Logo',
//										'name' => 'logo',
//										'type' => 'image',
//										'instructions' => '',
//										'required' => 0,
//										'conditional_logic' => 0,
//										'wrapper' => array(
//											'width' => '',
//											'class' => '',
//											'id' => '',
//										),
//										'show_in_graphql' => 1,
//										'return_format' => 'array',
//										'preview_size' => 'medium',
//										'library' => 'all',
//										'min_width' => '',
//										'min_height' => '',
//										'min_size' => '',
//										'max_width' => '',
//										'max_height' => '',
//										'max_size' => '',
//										'mime_types' => '',
//									),
//								),
//							),
//						),
//						'min' => '',
//						'max' => '',
//					),
//				),
//				'button_label' => 'Add Row',
//				'min' => '',
//				'max' => '',
//			),
//		),
//		'location' => array(
//			array(
//				array(
//					'param' => 'post_type',
//					'operator' => '==',
//					'value' => 'post',
//				),
//			),
//			array(
//				array(
//					'param' => 'post_type',
//					'operator' => '==',
//					'value' => 'news',
//				),
//			),
//			array(
//				array(
//					'param' => 'post_type',
//					'operator' => '==',
//					'value' => 'page',
//				),
//			),
//		),
//		'menu_order' => 0,
//		'position' => 'normal',
//		'style' => 'default',
//		'label_placement' => 'top',
//		'instruction_placement' => 'label',
//		'hide_on_screen' => '',
//		'active' => true,
//		'description' => '',
//		'show_in_graphql' => 1,
//		'graphql_field_name' => 'pageSections',
//		'map_graphql_types_from_location_rules' => 0,
//		'graphql_types' => '',
//	));
//
//endif;